showroom = set()
junkyard = {"Honda", "Jeep", "Ford","Nissan"}
showroom.add("Honda")
showroom.add("Jeep")
showroom.add("Mercedes")
showroom.add("Porsche")
showroom.add("Porsche")
showroom.update({"Lamborghini", "Maserati"})
showroom.discard('Porsche')
# print(showroom)
# print(junkyard.intersection(showroom))
showroom = showroom.union(junkyard)
print(showroom)
showroom.discard("Ford")
print(showroom)